// Returns generated by a given collection a spreadsheet document
//
Function GetSpreadDoc(Collection) 
	
	SpreadDoc = New SpreadsheetDocument;
	SpreadDoc.ReadOnly = True;
	SpreadDoc.ShowGrid = False;
	SpreadDoc.ShowHeaders = False;
		
	If TypeOf(Collection) = Type("Array") Then
	ColumnsNum = 1;
	
	Area = SpreadDoc.GetArea(1, 1, 1, ColumnsNum);
	
	Headers = New Structure;
	Area = SpreadDoc.GetArea(1, 1, 1, ColumnsNum);
	For Number = 1 по ColumnsNum Do
		FillingArea = Area.Area(1, Number, 1, Number);
		FillingArea.ColumnWidth = 100;
		FillingArea.Parameter = "Column1";
		FillingArea.DetailsParameter = "Column1";
		FillingArea.FillType = SpreadsheetDocumentAreaFillType.Parameter;
		FillingArea.DetailsUse = SpreadsheetDocumentDetailUse.Cell;
		FillingArea.Font = new Font(,12 , , , , ); 
	EndDo;
	Area.Parameters.Fill(Headers);
	SpreadDoc.Put(Area);
	
	For Each Item In Collection Do
		// Details
		For Number = 1 по ColumnsNum Do
			Area.Area(1,Number, 1, Number).DetailsParameter = "Column1";
			Area.Area(1,Number, 1, Number).Details = Item;
			Area.Area(1,Number, 1, Number).DetailsUse = SpreadsheetDocumentDetailUse.Cell;
			Area.Area(1,Number, 1, Number).TextPlacement = SpreadsheetDocumentTextPlacementType.Wrap;
			Area.Parameters["Column1"] = Item;
		EndDo;
		
		SpreadDoc.Put(Area);
	EndDo;
	Else
	ResCollection = Collection;	
	
	Line = New Line(SpreadsheetDocumentCellLineType.Solid);
	HeaderFont = new Font(,10,True); 
	TableFont = new Font(,8,False);  
	ColumnsNum = ResCollection.Columns.Count();
	
	Headers = New Structure;
	Area = SpreadDoc.GetArea(1, 1, 1, ColumnsNum);
	SpreadDoc.Вывести(Area);
	
	For Number = 1 по ColumnsNum Do
		FillingArea = Area.Area(1, Number, 1, Number);
		Column = ResCollection.Columns[Number-1];
		FillingArea.Parameter = Column.Name;
		FillingArea.DetailsParameter = Column.Name;
		FillingArea.Заполнение = SpreadsheetDocumentAreaFillType.Parameter;
		FillingArea.DetailsUse = SpreadsheetDocumentDetailUse.Cell;
		FillingArea.LeftBorder = Line;
		FillingArea.RightBorder = Line;
		FillingArea.TopBorder = Line;
		FillingArea.BottomBorder = Line;
		FillingArea.Font = HeaderFont;
						  
		Headers.Insert(Column.Name, Column.Name);
	EndDo;
	Area.Parameters.Fill(Headers);
	SpreadDoc.Put(Area);
	For Each Item In ResCollection Do
		// Details
		For Number = 1 по ColumnsNum Do
			Column = ResCollection.Columns[Number-1];
			CellArea = Area.Area(1,Number, 1, Number);
			CellArea.DetailsParameter = Column.Имя;
			CellArea.Details = Item[Column.Имя];
			CellArea.DetailsUse = SpreadsheetDocumentDetailUse.Cell;
			CellArea.TextPlacement = SpreadsheetDocumentTextPlacementType.Wrap;
			Area.Parameters[Column.Name] = Item[Column.Name];
			
			CellArea.LeftBorder = Line;
			CellArea.RightBorder = Line;
			CellArea.TopBorder = Line;
			CellArea.BottomBorder = Line;
			CellArea.Font = TableFont;
		EndDo;

		SpreadDoc.Put(Area);
	EndDo;
	
	EndIf; 
		
	Return SpreadDoc;
	
EndFunction
